import Head from "next/head";
import Link from "next/link";
import s from "../styles/components/layout.module.scss";

export const Layout = ({ title, children }) => {
  return (
    <div className={s.layout}>
      <Head>
        <title>{title | "Home page"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Solijonov web tutorials,Solijonov Qodirjon Blog"/>
        <meta name="author" content="Solijonov Qodirjon"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Link href={"/"}>
          <a>Home</a>
        </Link>
        <Link href={"/users"}>
          <a>Users</a>
        </Link>
        <Link href={"/blog"}>
          <a>Blog</a>
        </Link>
        <Link href={"/profile"}>
          <a>Profile</a>
        </Link>
      </nav>
      <main>{children}</main>
      <footer>
        <p>All right reserved 2022 year Creator Solijonov Qodirjon</p>
      </footer>
    </div>
  );
};
